name: CI/CD DockerHub to Cloud Run

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/home-inventory  # The full image name for Docker Hub
  SERVICE_NAME: home-inventory
  REGION: northamerica-south1                                            # Change to your region

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
            touch .env
            echo "${{secrets.TEST_SECRETS}}" >> .env


      # ------------------------ CI: BUILD & PUSH TO DOCKER HUB ------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Path to your Dockerfile
          push: true
          # Tagging with 'latest' and the Git SHA for traceability
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }} 

      # ------------------------ CD: DEPLOY TO GOOGLE CLOUD RUN ------------------------
      - name: Authenticate to Google Cloud (using SA Key)
        # This step uses the Service Account JSON key stored as a secret
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # Use the 'latest' tag which was just pushed to Docker Hub
          image: ${{ env.DOCKER_IMAGE }}:latest
          # Allows public (unauthenticated) access
          flags: '--allow-unauthenticated'
